package com.fkapi.datebase.dao;

import com.fkapi.datebase.domain.p2p_loan_claim_snapshoot;

import java.util.List;

public interface p2p_loan_claim_snapshootMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table p2p_loan_claim_snapshoot
     *
     * @mbggenerated
     */
    int deleteByCookie(String cookie);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table p2p_loan_claim_snapshoot
     *
     * @mbggenerated
     */
    int insert(List<p2p_loan_claim_snapshoot> list);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table p2p_loan_claim_snapshoot
     *
     * @mbggenerated
     */
    int insertSelective(p2p_loan_claim_snapshoot record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table p2p_loan_claim_snapshoot
     *
     * @mbggenerated
     */
    p2p_loan_claim_snapshoot selectByProjectNo(String projectNo);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table p2p_loan_claim_snapshoot
     *
     * @mbggenerated
     */
    int updateByPrimaryKeySelective(p2p_loan_claim_snapshoot record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table p2p_loan_claim_snapshoot
     *
     * @mbggenerated
     */
    int updateByPrimaryKey(p2p_loan_claim_snapshoot record);
}