package com.fkapi.datebase.dao;

import com.fkapi.datebase.domain.p2p_cooperation_employee_record;

public interface p2p_cooperation_employee_recordMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table p2p_cooperation_employee_record
     *
     * @mbggenerated
     */
    int deleteByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table p2p_cooperation_employee_record
     *
     * @mbggenerated
     */
    int insert(p2p_cooperation_employee_record record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table p2p_cooperation_employee_record
     *
     * @mbggenerated
     */
    int insertSelective(p2p_cooperation_employee_record record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table p2p_cooperation_employee_record
     *
     * @mbggenerated
     */
    p2p_cooperation_employee_record selectByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table p2p_cooperation_employee_record
     *
     * @mbggenerated
     */
    int updateByPrimaryKeySelective(p2p_cooperation_employee_record record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table p2p_cooperation_employee_record
     *
     * @mbggenerated
     */
    int updateByPrimaryKey(p2p_cooperation_employee_record record);
}