package com.fkapi.datebase.dao;

import com.fkapi.datebase.domain.p2p_cooperation_employee;

import java.util.List;

public interface p2p_cooperation_employeeMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table p2p_cooperation_employee
     *
     * @mbggenerated
     */
    int deleteByCompanyId(Long companyId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table p2p_cooperation_employee
     *
     * @mbggenerated
     */
    int insert(List<p2p_cooperation_employee> list);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table p2p_cooperation_employee
     *
     * @mbggenerated
     */
    int insertSelective(p2p_cooperation_employee record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table p2p_cooperation_employee
     *
     * @mbggenerated
     */
    p2p_cooperation_employee selectByCertNo(String certNo);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table p2p_cooperation_employee
     *
     * @mbggenerated
     */
    int updateByCertNo(p2p_cooperation_employee record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table p2p_cooperation_employee
     *
     * @mbggenerated
     */
    int updateByPrimaryKey(p2p_cooperation_employee record);
}