package com.fkapi.datebase.dao;

import com.fkapi.datebase.domain.vcc_customer;

import java.util.List;

public interface vcc_customerMapper {

    int deleteByLoginName(String loginName);

    int deleteByMobileSign(String mobileSign);

    int insert(List<vcc_customer> list);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table vcc_customer
     *
     * @mbg.generated
     */
    int insertSelective(vcc_customer record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table vcc_customer
     *
     * @mbg.generated
     */
    List<Long> selectByMobileSign(String mobileSign);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table vcc_customer
     *
     * @mbg.generated
     */
    int updateByPrimaryKeySelective(vcc_customer record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table vcc_customer
     *
     * @mbg.generated
     */
    int updateByPrimaryKey(vcc_customer record);
}