package com.fkapi.datebase.dao;

import com.fkapi.datebase.domain.vcc_cust_biz;

import java.util.List;

public interface vcc_cust_bizMapper {

    int deleteByCustId(List<Long> list);

    int insert(List<vcc_cust_biz> list);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table vcc_cust_biz
     *
     * @mbg.generated
     */
    int insertSelective(vcc_cust_biz record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table vcc_cust_biz
     *
     * @mbg.generated
     */
    vcc_cust_biz selectByPrimaryKey(Long custId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table vcc_cust_biz
     *
     * @mbg.generated
     */
    int updateByPrimaryKeySelective(vcc_cust_biz record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table vcc_cust_biz
     *
     * @mbg.generated
     */
    int updateByPrimaryKey(vcc_cust_biz record);
}