package com.fkapi.datebase.dao;

import com.fkapi.datebase.domain.vcc_order;

import java.util.List;

public interface vcc_orderMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table vcc_order
     *
     * @mbg.generated
     */
    int deleteByCarNo(String cardNo);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table vcc_order
     *
     * @mbg.generated
     */
    int insert(List<vcc_order> list);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table vcc_order
     *
     * @mbg.generated
     */
    int insertSelective(vcc_order record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table vcc_order
     *
     * @mbg.generated
     */
    vcc_order selectByPrimaryKey(String orderNo);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table vcc_order
     *
     * @mbg.generated
     */
    int updateByPrimaryKeySelective(vcc_order record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table vcc_order
     *
     * @mbg.generated
     */
    int updateByPrimaryKey(vcc_order record);
}