package com.fkapi.datebase.domain;

import java.util.Date;

public class p2p_cooperation_company {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column p2p_cooperation_company.id
     *
     * @mbggenerated
     */
    private Long id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column p2p_cooperation_company.company_id
     *
     * @mbggenerated
     */
    private Long companyId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column p2p_cooperation_company.group_name
     *
     * @mbggenerated
     */
    private String groupName;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column p2p_cooperation_company.company_name
     *
     * @mbggenerated
     */
    private String companyName;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column p2p_cooperation_company.industry_category
     *
     * @mbggenerated
     */
    private String industryCategory;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column p2p_cooperation_company.company_nature
     *
     * @mbggenerated
     */
    private Integer companyNature;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column p2p_cooperation_company.company_scale
     *
     * @mbggenerated
     */
    private String companyScale;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column p2p_cooperation_company.company_scale_max
     *
     * @mbggenerated
     */
    private Integer companyScaleMax;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column p2p_cooperation_company.company_scale_min
     *
     * @mbggenerated
     */
    private Integer companyScaleMin;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column p2p_cooperation_company.company_province
     *
     * @mbggenerated
     */
    private String companyProvince;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column p2p_cooperation_company.company_province_code
     *
     * @mbggenerated
     */
    private String companyProvinceCode;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column p2p_cooperation_company.company_city
     *
     * @mbggenerated
     */
    private String companyCity;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column p2p_cooperation_company.company_city_code
     *
     * @mbggenerated
     */
    private String companyCityCode;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column p2p_cooperation_company.create_time
     *
     * @mbggenerated
     */
    private Date createTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column p2p_cooperation_company.update_time
     *
     * @mbggenerated
     */
    private Date updateTime;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column p2p_cooperation_company.id
     *
     * @return the value of p2p_cooperation_company.id
     *
     * @mbggenerated
     */
    public Long getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column p2p_cooperation_company.id
     *
     * @param id the value for p2p_cooperation_company.id
     *
     * @mbggenerated
     */
    public void setId(Long id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column p2p_cooperation_company.company_id
     *
     * @return the value of p2p_cooperation_company.company_id
     *
     * @mbggenerated
     */
    public Long getCompanyId() {
        return companyId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column p2p_cooperation_company.company_id
     *
     * @param companyId the value for p2p_cooperation_company.company_id
     *
     * @mbggenerated
     */
    public void setCompanyId(Long companyId) {
        this.companyId = companyId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column p2p_cooperation_company.group_name
     *
     * @return the value of p2p_cooperation_company.group_name
     *
     * @mbggenerated
     */
    public String getGroupName() {
        return groupName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column p2p_cooperation_company.group_name
     *
     * @param groupName the value for p2p_cooperation_company.group_name
     *
     * @mbggenerated
     */
    public void setGroupName(String groupName) {
        this.groupName = groupName == null ? null : groupName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column p2p_cooperation_company.company_name
     *
     * @return the value of p2p_cooperation_company.company_name
     *
     * @mbggenerated
     */
    public String getCompanyName() {
        return companyName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column p2p_cooperation_company.company_name
     *
     * @param companyName the value for p2p_cooperation_company.company_name
     *
     * @mbggenerated
     */
    public void setCompanyName(String companyName) {
        this.companyName = companyName == null ? null : companyName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column p2p_cooperation_company.industry_category
     *
     * @return the value of p2p_cooperation_company.industry_category
     *
     * @mbggenerated
     */
    public String getIndustryCategory() {
        return industryCategory;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column p2p_cooperation_company.industry_category
     *
     * @param industryCategory the value for p2p_cooperation_company.industry_category
     *
     * @mbggenerated
     */
    public void setIndustryCategory(String industryCategory) {
        this.industryCategory = industryCategory == null ? null : industryCategory.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column p2p_cooperation_company.company_nature
     *
     * @return the value of p2p_cooperation_company.company_nature
     *
     * @mbggenerated
     */
    public Integer getCompanyNature() {
        return companyNature;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column p2p_cooperation_company.company_nature
     *
     * @param companyNature the value for p2p_cooperation_company.company_nature
     *
     * @mbggenerated
     */
    public void setCompanyNature(Integer companyNature) {
        this.companyNature = companyNature;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column p2p_cooperation_company.company_scale
     *
     * @return the value of p2p_cooperation_company.company_scale
     *
     * @mbggenerated
     */
    public String getCompanyScale() {
        return companyScale;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column p2p_cooperation_company.company_scale
     *
     * @param companyScale the value for p2p_cooperation_company.company_scale
     *
     * @mbggenerated
     */
    public void setCompanyScale(String companyScale) {
        this.companyScale = companyScale == null ? null : companyScale.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column p2p_cooperation_company.company_scale_max
     *
     * @return the value of p2p_cooperation_company.company_scale_max
     *
     * @mbggenerated
     */
    public Integer getCompanyScaleMax() {
        return companyScaleMax;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column p2p_cooperation_company.company_scale_max
     *
     * @param companyScaleMax the value for p2p_cooperation_company.company_scale_max
     *
     * @mbggenerated
     */
    public void setCompanyScaleMax(Integer companyScaleMax) {
        this.companyScaleMax = companyScaleMax;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column p2p_cooperation_company.company_scale_min
     *
     * @return the value of p2p_cooperation_company.company_scale_min
     *
     * @mbggenerated
     */
    public Integer getCompanyScaleMin() {
        return companyScaleMin;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column p2p_cooperation_company.company_scale_min
     *
     * @param companyScaleMin the value for p2p_cooperation_company.company_scale_min
     *
     * @mbggenerated
     */
    public void setCompanyScaleMin(Integer companyScaleMin) {
        this.companyScaleMin = companyScaleMin;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column p2p_cooperation_company.company_province
     *
     * @return the value of p2p_cooperation_company.company_province
     *
     * @mbggenerated
     */
    public String getCompanyProvince() {
        return companyProvince;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column p2p_cooperation_company.company_province
     *
     * @param companyProvince the value for p2p_cooperation_company.company_province
     *
     * @mbggenerated
     */
    public void setCompanyProvince(String companyProvince) {
        this.companyProvince = companyProvince == null ? null : companyProvince.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column p2p_cooperation_company.company_province_code
     *
     * @return the value of p2p_cooperation_company.company_province_code
     *
     * @mbggenerated
     */
    public String getCompanyProvinceCode() {
        return companyProvinceCode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column p2p_cooperation_company.company_province_code
     *
     * @param companyProvinceCode the value for p2p_cooperation_company.company_province_code
     *
     * @mbggenerated
     */
    public void setCompanyProvinceCode(String companyProvinceCode) {
        this.companyProvinceCode = companyProvinceCode == null ? null : companyProvinceCode.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column p2p_cooperation_company.company_city
     *
     * @return the value of p2p_cooperation_company.company_city
     *
     * @mbggenerated
     */
    public String getCompanyCity() {
        return companyCity;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column p2p_cooperation_company.company_city
     *
     * @param companyCity the value for p2p_cooperation_company.company_city
     *
     * @mbggenerated
     */
    public void setCompanyCity(String companyCity) {
        this.companyCity = companyCity == null ? null : companyCity.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column p2p_cooperation_company.company_city_code
     *
     * @return the value of p2p_cooperation_company.company_city_code
     *
     * @mbggenerated
     */
    public String getCompanyCityCode() {
        return companyCityCode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column p2p_cooperation_company.company_city_code
     *
     * @param companyCityCode the value for p2p_cooperation_company.company_city_code
     *
     * @mbggenerated
     */
    public void setCompanyCityCode(String companyCityCode) {
        this.companyCityCode = companyCityCode == null ? null : companyCityCode.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column p2p_cooperation_company.create_time
     *
     * @return the value of p2p_cooperation_company.create_time
     *
     * @mbggenerated
     */
    public Date getCreateTime() {
        return createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column p2p_cooperation_company.create_time
     *
     * @param createTime the value for p2p_cooperation_company.create_time
     *
     * @mbggenerated
     */
    public void setCreateTime(Date createTime) {
        this.createTime = createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column p2p_cooperation_company.update_time
     *
     * @return the value of p2p_cooperation_company.update_time
     *
     * @mbggenerated
     */
    public Date getUpdateTime() {
        return updateTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column p2p_cooperation_company.update_time
     *
     * @param updateTime the value for p2p_cooperation_company.update_time
     *
     * @mbggenerated
     */
    public void setUpdateTime(Date updateTime) {
        this.updateTime = updateTime;
    }
}