package com.fkapi.datebase.domain;

import java.util.Date;

public class p2p_loan_claim_snapshoot {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column p2p_loan_claim_snapshoot.project_no
     *
     * @mbggenerated
     */
    private String projectNo;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column p2p_loan_claim_snapshoot.cust_id
     *
     * @mbggenerated
     */
    private Long custId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column p2p_loan_claim_snapshoot.ip
     *
     * @mbggenerated
     */
    private String ip;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column p2p_loan_claim_snapshoot.ip_city_code
     *
     * @mbggenerated
     */
    private String ipCityCode;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column p2p_loan_claim_snapshoot.cookie
     *
     * @mbggenerated
     */
    private String cookie;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column p2p_loan_claim_snapshoot.mobile_sign
     *
     * @mbggenerated
     */
    private String mobileSign;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column p2p_loan_claim_snapshoot.phone_tel
     *
     * @mbggenerated
     */
    private String phoneTel;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column p2p_loan_claim_snapshoot.mobile_os
     *
     * @mbggenerated
     */
    private String mobileOs;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column p2p_loan_claim_snapshoot.gps_info
     *
     * @mbggenerated
     */
    private String gpsInfo;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column p2p_loan_claim_snapshoot.sim_code
     *
     * @mbggenerated
     */
    private String simCode;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column p2p_loan_claim_snapshoot.mac_addr
     *
     * @mbggenerated
     */
    private String macAddr;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column p2p_loan_claim_snapshoot.app_version
     *
     * @mbggenerated
     */
    private String appVersion;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column p2p_loan_claim_snapshoot.credit_amount
     *
     * @mbggenerated
     */
    private Long creditAmount;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column p2p_loan_claim_snapshoot.company_id
     *
     * @mbggenerated
     */
    private Long companyId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column p2p_loan_claim_snapshoot.project_type
     *
     * @mbggenerated
     */
    private String projectType;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column p2p_loan_claim_snapshoot.project_sub_type
     *
     * @mbggenerated
     */
    private String projectSubType;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column p2p_loan_claim_snapshoot.create_time
     *
     * @mbggenerated
     */
    private Date createTime;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column p2p_loan_claim_snapshoot.project_no
     *
     * @return the value of p2p_loan_claim_snapshoot.project_no
     *
     * @mbggenerated
     */
    public String getProjectNo() {
        return projectNo;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column p2p_loan_claim_snapshoot.project_no
     *
     * @param projectNo the value for p2p_loan_claim_snapshoot.project_no
     *
     * @mbggenerated
     */
    public void setProjectNo(String projectNo) {
        this.projectNo = projectNo == null ? null : projectNo.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column p2p_loan_claim_snapshoot.cust_id
     *
     * @return the value of p2p_loan_claim_snapshoot.cust_id
     *
     * @mbggenerated
     */
    public Long getCustId() {
        return custId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column p2p_loan_claim_snapshoot.cust_id
     *
     * @param custId the value for p2p_loan_claim_snapshoot.cust_id
     *
     * @mbggenerated
     */
    public void setCustId(Long custId) {
        this.custId = custId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column p2p_loan_claim_snapshoot.ip
     *
     * @return the value of p2p_loan_claim_snapshoot.ip
     *
     * @mbggenerated
     */
    public String getIp() {
        return ip;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column p2p_loan_claim_snapshoot.ip
     *
     * @param ip the value for p2p_loan_claim_snapshoot.ip
     *
     * @mbggenerated
     */
    public void setIp(String ip) {
        this.ip = ip == null ? null : ip.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column p2p_loan_claim_snapshoot.ip_city_code
     *
     * @return the value of p2p_loan_claim_snapshoot.ip_city_code
     *
     * @mbggenerated
     */
    public String getIpCityCode() {
        return ipCityCode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column p2p_loan_claim_snapshoot.ip_city_code
     *
     * @param ipCityCode the value for p2p_loan_claim_snapshoot.ip_city_code
     *
     * @mbggenerated
     */
    public void setIpCityCode(String ipCityCode) {
        this.ipCityCode = ipCityCode == null ? null : ipCityCode.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column p2p_loan_claim_snapshoot.cookie
     *
     * @return the value of p2p_loan_claim_snapshoot.cookie
     *
     * @mbggenerated
     */
    public String getCookie() {
        return cookie;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column p2p_loan_claim_snapshoot.cookie
     *
     * @param cookie the value for p2p_loan_claim_snapshoot.cookie
     *
     * @mbggenerated
     */
    public void setCookie(String cookie) {
        this.cookie = cookie == null ? null : cookie.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column p2p_loan_claim_snapshoot.mobile_sign
     *
     * @return the value of p2p_loan_claim_snapshoot.mobile_sign
     *
     * @mbggenerated
     */
    public String getMobileSign() {
        return mobileSign;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column p2p_loan_claim_snapshoot.mobile_sign
     *
     * @param mobileSign the value for p2p_loan_claim_snapshoot.mobile_sign
     *
     * @mbggenerated
     */
    public void setMobileSign(String mobileSign) {
        this.mobileSign = mobileSign == null ? null : mobileSign.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column p2p_loan_claim_snapshoot.phone_tel
     *
     * @return the value of p2p_loan_claim_snapshoot.phone_tel
     *
     * @mbggenerated
     */
    public String getPhoneTel() {
        return phoneTel;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column p2p_loan_claim_snapshoot.phone_tel
     *
     * @param phoneTel the value for p2p_loan_claim_snapshoot.phone_tel
     *
     * @mbggenerated
     */
    public void setPhoneTel(String phoneTel) {
        this.phoneTel = phoneTel == null ? null : phoneTel.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column p2p_loan_claim_snapshoot.mobile_os
     *
     * @return the value of p2p_loan_claim_snapshoot.mobile_os
     *
     * @mbggenerated
     */
    public String getMobileOs() {
        return mobileOs;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column p2p_loan_claim_snapshoot.mobile_os
     *
     * @param mobileOs the value for p2p_loan_claim_snapshoot.mobile_os
     *
     * @mbggenerated
     */
    public void setMobileOs(String mobileOs) {
        this.mobileOs = mobileOs == null ? null : mobileOs.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column p2p_loan_claim_snapshoot.gps_info
     *
     * @return the value of p2p_loan_claim_snapshoot.gps_info
     *
     * @mbggenerated
     */
    public String getGpsInfo() {
        return gpsInfo;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column p2p_loan_claim_snapshoot.gps_info
     *
     * @param gpsInfo the value for p2p_loan_claim_snapshoot.gps_info
     *
     * @mbggenerated
     */
    public void setGpsInfo(String gpsInfo) {
        this.gpsInfo = gpsInfo == null ? null : gpsInfo.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column p2p_loan_claim_snapshoot.sim_code
     *
     * @return the value of p2p_loan_claim_snapshoot.sim_code
     *
     * @mbggenerated
     */
    public String getSimCode() {
        return simCode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column p2p_loan_claim_snapshoot.sim_code
     *
     * @param simCode the value for p2p_loan_claim_snapshoot.sim_code
     *
     * @mbggenerated
     */
    public void setSimCode(String simCode) {
        this.simCode = simCode == null ? null : simCode.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column p2p_loan_claim_snapshoot.mac_addr
     *
     * @return the value of p2p_loan_claim_snapshoot.mac_addr
     *
     * @mbggenerated
     */
    public String getMacAddr() {
        return macAddr;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column p2p_loan_claim_snapshoot.mac_addr
     *
     * @param macAddr the value for p2p_loan_claim_snapshoot.mac_addr
     *
     * @mbggenerated
     */
    public void setMacAddr(String macAddr) {
        this.macAddr = macAddr == null ? null : macAddr.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column p2p_loan_claim_snapshoot.app_version
     *
     * @return the value of p2p_loan_claim_snapshoot.app_version
     *
     * @mbggenerated
     */
    public String getAppVersion() {
        return appVersion;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column p2p_loan_claim_snapshoot.app_version
     *
     * @param appVersion the value for p2p_loan_claim_snapshoot.app_version
     *
     * @mbggenerated
     */
    public void setAppVersion(String appVersion) {
        this.appVersion = appVersion == null ? null : appVersion.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column p2p_loan_claim_snapshoot.credit_amount
     *
     * @return the value of p2p_loan_claim_snapshoot.credit_amount
     *
     * @mbggenerated
     */
    public Long getCreditAmount() {
        return creditAmount;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column p2p_loan_claim_snapshoot.credit_amount
     *
     * @param creditAmount the value for p2p_loan_claim_snapshoot.credit_amount
     *
     * @mbggenerated
     */
    public void setCreditAmount(Long creditAmount) {
        this.creditAmount = creditAmount;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column p2p_loan_claim_snapshoot.company_id
     *
     * @return the value of p2p_loan_claim_snapshoot.company_id
     *
     * @mbggenerated
     */
    public Long getCompanyId() {
        return companyId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column p2p_loan_claim_snapshoot.company_id
     *
     * @param companyId the value for p2p_loan_claim_snapshoot.company_id
     *
     * @mbggenerated
     */
    public void setCompanyId(Long companyId) {
        this.companyId = companyId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column p2p_loan_claim_snapshoot.project_type
     *
     * @return the value of p2p_loan_claim_snapshoot.project_type
     *
     * @mbggenerated
     */
    public String getProjectType() {
        return projectType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column p2p_loan_claim_snapshoot.project_type
     *
     * @param projectType the value for p2p_loan_claim_snapshoot.project_type
     *
     * @mbggenerated
     */
    public void setProjectType(String projectType) {
        this.projectType = projectType == null ? null : projectType.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column p2p_loan_claim_snapshoot.project_sub_type
     *
     * @return the value of p2p_loan_claim_snapshoot.project_sub_type
     *
     * @mbggenerated
     */
    public String getProjectSubType() {
        return projectSubType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column p2p_loan_claim_snapshoot.project_sub_type
     *
     * @param projectSubType the value for p2p_loan_claim_snapshoot.project_sub_type
     *
     * @mbggenerated
     */
    public void setProjectSubType(String projectSubType) {
        this.projectSubType = projectSubType == null ? null : projectSubType.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column p2p_loan_claim_snapshoot.create_time
     *
     * @return the value of p2p_loan_claim_snapshoot.create_time
     *
     * @mbggenerated
     */
    public Date getCreateTime() {
        return createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column p2p_loan_claim_snapshoot.create_time
     *
     * @param createTime the value for p2p_loan_claim_snapshoot.create_time
     *
     * @mbggenerated
     */
    public void setCreateTime(Date createTime) {
        this.createTime = createTime;
    }
}