package com.fkapi.datebase.domain;

import java.math.BigDecimal;
import java.util.Date;

public class vcc_loan_info {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column vcc_loan_info.LOAN_NO
     *
     * @mbg.generated
     */
    private String loanNo;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column vcc_loan_info.ORDER_NO
     *
     * @mbg.generated
     */
    private String orderNo;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column vcc_loan_info.RELATIVE_LOAN_NO
     *
     * @mbg.generated
     */
    private String relativeLoanNo;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column vcc_loan_info.CUST_ID
     *
     * @mbg.generated
     */
    private Long custId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column vcc_loan_info.CARD_NO
     *
     * @mbg.generated
     */
    private String cardNo;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column vcc_loan_info.INTEREST_RATE
     *
     * @mbg.generated
     */
    private BigDecimal interestRate;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column vcc_loan_info.SERVICE_FEE_RATE
     *
     * @mbg.generated
     */
    private BigDecimal serviceFeeRate;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column vcc_loan_info.OVERDUE_RATE
     *
     * @mbg.generated
     */
    private BigDecimal overdueRate;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column vcc_loan_info.RETURN_FEE_RATE
     *
     * @mbg.generated
     */
    private BigDecimal returnFeeRate;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column vcc_loan_info.LOAN_AMOUNT
     *
     * @mbg.generated
     */
    private BigDecimal loanAmount;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column vcc_loan_info.RETURN_FEE
     *
     * @mbg.generated
     */
    private BigDecimal returnFee;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column vcc_loan_info.OVERDUE_MAMT_RATE
     *
     * @mbg.generated
     */
    private BigDecimal overdueMamtRate;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column vcc_loan_info.OVERDUE_MAMT_FEE
     *
     * @mbg.generated
     */
    private BigDecimal overdueMamtFee;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column vcc_loan_info.STATUS
     *
     * @mbg.generated
     */
    private String status;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column vcc_loan_info.REPAY_METHOD
     *
     * @mbg.generated
     */
    private String repayMethod;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column vcc_loan_info.OVERDUE_FLAG
     *
     * @mbg.generated
     */
    private String overdueFlag;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column vcc_loan_info.OVERDUE_DAYS
     *
     * @mbg.generated
     */
    private Integer overdueDays;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column vcc_loan_info.LOAN_DATE
     *
     * @mbg.generated
     */
    private Date loanDate;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column vcc_loan_info.DEADLINE
     *
     * @mbg.generated
     */
    private Date deadline;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column vcc_loan_info.CREATE_TIME
     *
     * @mbg.generated
     */
    private Date createTime;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column vcc_loan_info.UPDATE_TIME
     *
     * @mbg.generated
     */
    private Date updateTime;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column vcc_loan_info.VERSION
     *
     * @mbg.generated
     */
    private Long version;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column vcc_loan_info.LOAN_NO
     *
     * @return the value of vcc_loan_info.LOAN_NO
     *
     * @mbg.generated
     */
    public String getLoanNo() {
        return loanNo;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column vcc_loan_info.LOAN_NO
     *
     * @param loanNo the value for vcc_loan_info.LOAN_NO
     *
     * @mbg.generated
     */
    public void setLoanNo(String loanNo) {
        this.loanNo = loanNo == null ? null : loanNo.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column vcc_loan_info.ORDER_NO
     *
     * @return the value of vcc_loan_info.ORDER_NO
     *
     * @mbg.generated
     */
    public String getOrderNo() {
        return orderNo;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column vcc_loan_info.ORDER_NO
     *
     * @param orderNo the value for vcc_loan_info.ORDER_NO
     *
     * @mbg.generated
     */
    public void setOrderNo(String orderNo) {
        this.orderNo = orderNo == null ? null : orderNo.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column vcc_loan_info.RELATIVE_LOAN_NO
     *
     * @return the value of vcc_loan_info.RELATIVE_LOAN_NO
     *
     * @mbg.generated
     */
    public String getRelativeLoanNo() {
        return relativeLoanNo;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column vcc_loan_info.RELATIVE_LOAN_NO
     *
     * @param relativeLoanNo the value for vcc_loan_info.RELATIVE_LOAN_NO
     *
     * @mbg.generated
     */
    public void setRelativeLoanNo(String relativeLoanNo) {
        this.relativeLoanNo = relativeLoanNo == null ? null : relativeLoanNo.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column vcc_loan_info.CUST_ID
     *
     * @return the value of vcc_loan_info.CUST_ID
     *
     * @mbg.generated
     */
    public Long getCustId() {
        return custId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column vcc_loan_info.CUST_ID
     *
     * @param custId the value for vcc_loan_info.CUST_ID
     *
     * @mbg.generated
     */
    public void setCustId(Long custId) {
        this.custId = custId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column vcc_loan_info.CARD_NO
     *
     * @return the value of vcc_loan_info.CARD_NO
     *
     * @mbg.generated
     */
    public String getCardNo() {
        return cardNo;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column vcc_loan_info.CARD_NO
     *
     * @param cardNo the value for vcc_loan_info.CARD_NO
     *
     * @mbg.generated
     */
    public void setCardNo(String cardNo) {
        this.cardNo = cardNo == null ? null : cardNo.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column vcc_loan_info.INTEREST_RATE
     *
     * @return the value of vcc_loan_info.INTEREST_RATE
     *
     * @mbg.generated
     */
    public BigDecimal getInterestRate() {
        return interestRate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column vcc_loan_info.INTEREST_RATE
     *
     * @param interestRate the value for vcc_loan_info.INTEREST_RATE
     *
     * @mbg.generated
     */
    public void setInterestRate(BigDecimal interestRate) {
        this.interestRate = interestRate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column vcc_loan_info.SERVICE_FEE_RATE
     *
     * @return the value of vcc_loan_info.SERVICE_FEE_RATE
     *
     * @mbg.generated
     */
    public BigDecimal getServiceFeeRate() {
        return serviceFeeRate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column vcc_loan_info.SERVICE_FEE_RATE
     *
     * @param serviceFeeRate the value for vcc_loan_info.SERVICE_FEE_RATE
     *
     * @mbg.generated
     */
    public void setServiceFeeRate(BigDecimal serviceFeeRate) {
        this.serviceFeeRate = serviceFeeRate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column vcc_loan_info.OVERDUE_RATE
     *
     * @return the value of vcc_loan_info.OVERDUE_RATE
     *
     * @mbg.generated
     */
    public BigDecimal getOverdueRate() {
        return overdueRate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column vcc_loan_info.OVERDUE_RATE
     *
     * @param overdueRate the value for vcc_loan_info.OVERDUE_RATE
     *
     * @mbg.generated
     */
    public void setOverdueRate(BigDecimal overdueRate) {
        this.overdueRate = overdueRate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column vcc_loan_info.RETURN_FEE_RATE
     *
     * @return the value of vcc_loan_info.RETURN_FEE_RATE
     *
     * @mbg.generated
     */
    public BigDecimal getReturnFeeRate() {
        return returnFeeRate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column vcc_loan_info.RETURN_FEE_RATE
     *
     * @param returnFeeRate the value for vcc_loan_info.RETURN_FEE_RATE
     *
     * @mbg.generated
     */
    public void setReturnFeeRate(BigDecimal returnFeeRate) {
        this.returnFeeRate = returnFeeRate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column vcc_loan_info.LOAN_AMOUNT
     *
     * @return the value of vcc_loan_info.LOAN_AMOUNT
     *
     * @mbg.generated
     */
    public BigDecimal getLoanAmount() {
        return loanAmount;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column vcc_loan_info.LOAN_AMOUNT
     *
     * @param loanAmount the value for vcc_loan_info.LOAN_AMOUNT
     *
     * @mbg.generated
     */
    public void setLoanAmount(BigDecimal loanAmount) {
        this.loanAmount = loanAmount;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column vcc_loan_info.RETURN_FEE
     *
     * @return the value of vcc_loan_info.RETURN_FEE
     *
     * @mbg.generated
     */
    public BigDecimal getReturnFee() {
        return returnFee;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column vcc_loan_info.RETURN_FEE
     *
     * @param returnFee the value for vcc_loan_info.RETURN_FEE
     *
     * @mbg.generated
     */
    public void setReturnFee(BigDecimal returnFee) {
        this.returnFee = returnFee;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column vcc_loan_info.OVERDUE_MAMT_RATE
     *
     * @return the value of vcc_loan_info.OVERDUE_MAMT_RATE
     *
     * @mbg.generated
     */
    public BigDecimal getOverdueMamtRate() {
        return overdueMamtRate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column vcc_loan_info.OVERDUE_MAMT_RATE
     *
     * @param overdueMamtRate the value for vcc_loan_info.OVERDUE_MAMT_RATE
     *
     * @mbg.generated
     */
    public void setOverdueMamtRate(BigDecimal overdueMamtRate) {
        this.overdueMamtRate = overdueMamtRate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column vcc_loan_info.OVERDUE_MAMT_FEE
     *
     * @return the value of vcc_loan_info.OVERDUE_MAMT_FEE
     *
     * @mbg.generated
     */
    public BigDecimal getOverdueMamtFee() {
        return overdueMamtFee;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column vcc_loan_info.OVERDUE_MAMT_FEE
     *
     * @param overdueMamtFee the value for vcc_loan_info.OVERDUE_MAMT_FEE
     *
     * @mbg.generated
     */
    public void setOverdueMamtFee(BigDecimal overdueMamtFee) {
        this.overdueMamtFee = overdueMamtFee;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column vcc_loan_info.STATUS
     *
     * @return the value of vcc_loan_info.STATUS
     *
     * @mbg.generated
     */
    public String getStatus() {
        return status;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column vcc_loan_info.STATUS
     *
     * @param status the value for vcc_loan_info.STATUS
     *
     * @mbg.generated
     */
    public void setStatus(String status) {
        this.status = status == null ? null : status.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column vcc_loan_info.REPAY_METHOD
     *
     * @return the value of vcc_loan_info.REPAY_METHOD
     *
     * @mbg.generated
     */
    public String getRepayMethod() {
        return repayMethod;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column vcc_loan_info.REPAY_METHOD
     *
     * @param repayMethod the value for vcc_loan_info.REPAY_METHOD
     *
     * @mbg.generated
     */
    public void setRepayMethod(String repayMethod) {
        this.repayMethod = repayMethod == null ? null : repayMethod.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column vcc_loan_info.OVERDUE_FLAG
     *
     * @return the value of vcc_loan_info.OVERDUE_FLAG
     *
     * @mbg.generated
     */
    public String getOverdueFlag() {
        return overdueFlag;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column vcc_loan_info.OVERDUE_FLAG
     *
     * @param overdueFlag the value for vcc_loan_info.OVERDUE_FLAG
     *
     * @mbg.generated
     */
    public void setOverdueFlag(String overdueFlag) {
        this.overdueFlag = overdueFlag == null ? null : overdueFlag.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column vcc_loan_info.OVERDUE_DAYS
     *
     * @return the value of vcc_loan_info.OVERDUE_DAYS
     *
     * @mbg.generated
     */
    public Integer getOverdueDays() {
        return overdueDays;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column vcc_loan_info.OVERDUE_DAYS
     *
     * @param overdueDays the value for vcc_loan_info.OVERDUE_DAYS
     *
     * @mbg.generated
     */
    public void setOverdueDays(Integer overdueDays) {
        this.overdueDays = overdueDays;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column vcc_loan_info.LOAN_DATE
     *
     * @return the value of vcc_loan_info.LOAN_DATE
     *
     * @mbg.generated
     */
    public Date getLoanDate() {
        return loanDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column vcc_loan_info.LOAN_DATE
     *
     * @param loanDate the value for vcc_loan_info.LOAN_DATE
     *
     * @mbg.generated
     */
    public void setLoanDate(Date loanDate) {
        this.loanDate = loanDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column vcc_loan_info.DEADLINE
     *
     * @return the value of vcc_loan_info.DEADLINE
     *
     * @mbg.generated
     */
    public Date getDeadline() {
        return deadline;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column vcc_loan_info.DEADLINE
     *
     * @param deadline the value for vcc_loan_info.DEADLINE
     *
     * @mbg.generated
     */
    public void setDeadline(Date deadline) {
        this.deadline = deadline;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column vcc_loan_info.CREATE_TIME
     *
     * @return the value of vcc_loan_info.CREATE_TIME
     *
     * @mbg.generated
     */
    public Date getCreateTime() {
        return createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column vcc_loan_info.CREATE_TIME
     *
     * @param createTime the value for vcc_loan_info.CREATE_TIME
     *
     * @mbg.generated
     */
    public void setCreateTime(Date createTime) {
        this.createTime = createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column vcc_loan_info.UPDATE_TIME
     *
     * @return the value of vcc_loan_info.UPDATE_TIME
     *
     * @mbg.generated
     */
    public Date getUpdateTime() {
        return updateTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column vcc_loan_info.UPDATE_TIME
     *
     * @param updateTime the value for vcc_loan_info.UPDATE_TIME
     *
     * @mbg.generated
     */
    public void setUpdateTime(Date updateTime) {
        this.updateTime = updateTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column vcc_loan_info.VERSION
     *
     * @return the value of vcc_loan_info.VERSION
     *
     * @mbg.generated
     */
    public Long getVersion() {
        return version;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column vcc_loan_info.VERSION
     *
     * @param version the value for vcc_loan_info.VERSION
     *
     * @mbg.generated
     */
    public void setVersion(Long version) {
        this.version = version;
    }
}