package com.fkapi.datebase.domain;

import java.util.Date;

public class vcc_user_card_map {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column vcc_user_card_map.ID
     *
     * @mbg.generated
     */
    private Long id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column vcc_user_card_map.CUST_ID
     *
     * @mbg.generated
     */
    private Long custId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column vcc_user_card_map.CARD_NO
     *
     * @mbg.generated
     */
    private String cardNo;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column vcc_user_card_map.STATUS
     *
     * @mbg.generated
     */
    private String status;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column vcc_user_card_map.CERT_STATUS
     *
     * @mbg.generated
     */
    private String certStatus;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column vcc_user_card_map.MOBILE_STATUS
     *
     * @mbg.generated
     */
    private String mobileStatus;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column vcc_user_card_map.CARD_STATUS
     *
     * @mbg.generated
     */
    private String cardStatus;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column vcc_user_card_map.CERT_AUTH_TIME
     *
     * @mbg.generated
     */
    private Date certAuthTime;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column vcc_user_card_map.MOBILE_AUTH_TIME
     *
     * @mbg.generated
     */
    private Date mobileAuthTime;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column vcc_user_card_map.CARD_AUTH_TIME
     *
     * @mbg.generated
     */
    private Date cardAuthTime;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column vcc_user_card_map.RELATIVE_TIME
     *
     * @mbg.generated
     */
    private Date relativeTime;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column vcc_user_card_map.CREATE_TIME
     *
     * @mbg.generated
     */
    private Date createTime;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column vcc_user_card_map.UPDATE_TIME
     *
     * @mbg.generated
     */
    private Date updateTime;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column vcc_user_card_map.ID
     *
     * @return the value of vcc_user_card_map.ID
     *
     * @mbg.generated
     */
    public Long getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column vcc_user_card_map.ID
     *
     * @param id the value for vcc_user_card_map.ID
     *
     * @mbg.generated
     */
    public void setId(Long id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column vcc_user_card_map.CUST_ID
     *
     * @return the value of vcc_user_card_map.CUST_ID
     *
     * @mbg.generated
     */
    public Long getCustId() {
        return custId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column vcc_user_card_map.CUST_ID
     *
     * @param custId the value for vcc_user_card_map.CUST_ID
     *
     * @mbg.generated
     */
    public void setCustId(Long custId) {
        this.custId = custId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column vcc_user_card_map.CARD_NO
     *
     * @return the value of vcc_user_card_map.CARD_NO
     *
     * @mbg.generated
     */
    public String getCardNo() {
        return cardNo;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column vcc_user_card_map.CARD_NO
     *
     * @param cardNo the value for vcc_user_card_map.CARD_NO
     *
     * @mbg.generated
     */
    public void setCardNo(String cardNo) {
        this.cardNo = cardNo == null ? null : cardNo.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column vcc_user_card_map.STATUS
     *
     * @return the value of vcc_user_card_map.STATUS
     *
     * @mbg.generated
     */
    public String getStatus() {
        return status;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column vcc_user_card_map.STATUS
     *
     * @param status the value for vcc_user_card_map.STATUS
     *
     * @mbg.generated
     */
    public void setStatus(String status) {
        this.status = status == null ? null : status.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column vcc_user_card_map.CERT_STATUS
     *
     * @return the value of vcc_user_card_map.CERT_STATUS
     *
     * @mbg.generated
     */
    public String getCertStatus() {
        return certStatus;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column vcc_user_card_map.CERT_STATUS
     *
     * @param certStatus the value for vcc_user_card_map.CERT_STATUS
     *
     * @mbg.generated
     */
    public void setCertStatus(String certStatus) {
        this.certStatus = certStatus == null ? null : certStatus.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column vcc_user_card_map.MOBILE_STATUS
     *
     * @return the value of vcc_user_card_map.MOBILE_STATUS
     *
     * @mbg.generated
     */
    public String getMobileStatus() {
        return mobileStatus;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column vcc_user_card_map.MOBILE_STATUS
     *
     * @param mobileStatus the value for vcc_user_card_map.MOBILE_STATUS
     *
     * @mbg.generated
     */
    public void setMobileStatus(String mobileStatus) {
        this.mobileStatus = mobileStatus == null ? null : mobileStatus.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column vcc_user_card_map.CARD_STATUS
     *
     * @return the value of vcc_user_card_map.CARD_STATUS
     *
     * @mbg.generated
     */
    public String getCardStatus() {
        return cardStatus;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column vcc_user_card_map.CARD_STATUS
     *
     * @param cardStatus the value for vcc_user_card_map.CARD_STATUS
     *
     * @mbg.generated
     */
    public void setCardStatus(String cardStatus) {
        this.cardStatus = cardStatus == null ? null : cardStatus.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column vcc_user_card_map.CERT_AUTH_TIME
     *
     * @return the value of vcc_user_card_map.CERT_AUTH_TIME
     *
     * @mbg.generated
     */
    public Date getCertAuthTime() {
        return certAuthTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column vcc_user_card_map.CERT_AUTH_TIME
     *
     * @param certAuthTime the value for vcc_user_card_map.CERT_AUTH_TIME
     *
     * @mbg.generated
     */
    public void setCertAuthTime(Date certAuthTime) {
        this.certAuthTime = certAuthTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column vcc_user_card_map.MOBILE_AUTH_TIME
     *
     * @return the value of vcc_user_card_map.MOBILE_AUTH_TIME
     *
     * @mbg.generated
     */
    public Date getMobileAuthTime() {
        return mobileAuthTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column vcc_user_card_map.MOBILE_AUTH_TIME
     *
     * @param mobileAuthTime the value for vcc_user_card_map.MOBILE_AUTH_TIME
     *
     * @mbg.generated
     */
    public void setMobileAuthTime(Date mobileAuthTime) {
        this.mobileAuthTime = mobileAuthTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column vcc_user_card_map.CARD_AUTH_TIME
     *
     * @return the value of vcc_user_card_map.CARD_AUTH_TIME
     *
     * @mbg.generated
     */
    public Date getCardAuthTime() {
        return cardAuthTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column vcc_user_card_map.CARD_AUTH_TIME
     *
     * @param cardAuthTime the value for vcc_user_card_map.CARD_AUTH_TIME
     *
     * @mbg.generated
     */
    public void setCardAuthTime(Date cardAuthTime) {
        this.cardAuthTime = cardAuthTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column vcc_user_card_map.RELATIVE_TIME
     *
     * @return the value of vcc_user_card_map.RELATIVE_TIME
     *
     * @mbg.generated
     */
    public Date getRelativeTime() {
        return relativeTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column vcc_user_card_map.RELATIVE_TIME
     *
     * @param relativeTime the value for vcc_user_card_map.RELATIVE_TIME
     *
     * @mbg.generated
     */
    public void setRelativeTime(Date relativeTime) {
        this.relativeTime = relativeTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column vcc_user_card_map.CREATE_TIME
     *
     * @return the value of vcc_user_card_map.CREATE_TIME
     *
     * @mbg.generated
     */
    public Date getCreateTime() {
        return createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column vcc_user_card_map.CREATE_TIME
     *
     * @param createTime the value for vcc_user_card_map.CREATE_TIME
     *
     * @mbg.generated
     */
    public void setCreateTime(Date createTime) {
        this.createTime = createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column vcc_user_card_map.UPDATE_TIME
     *
     * @return the value of vcc_user_card_map.UPDATE_TIME
     *
     * @mbg.generated
     */
    public Date getUpdateTime() {
        return updateTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column vcc_user_card_map.UPDATE_TIME
     *
     * @param updateTime the value for vcc_user_card_map.UPDATE_TIME
     *
     * @mbg.generated
     */
    public void setUpdateTime(Date updateTime) {
        this.updateTime = updateTime;
    }
}