package com.fkapi.datebase.domain;

import java.util.Date;

public class vcc_customer {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column vcc_customer.CUST_ID
     *
     * @mbg.generated
     */
    private Long custId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column vcc_customer.LOGIN_NAME
     *
     * @mbg.generated
     */
    private String loginName;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column vcc_customer.CUST_NAME
     *
     * @mbg.generated
     */
    private String custName;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column vcc_customer.CERT_NO
     *
     * @mbg.generated
     */
    private String certNo;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column vcc_customer.SEX
     *
     * @mbg.generated
     */
    private String sex;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column vcc_customer.AGE
     *
     * @mbg.generated
     */
    private Short age;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column vcc_customer.MOBILE
     *
     * @mbg.generated
     */
    private String mobile;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column vcc_customer.REG_TIME
     *
     * @mbg.generated
     */
    private Date regTime;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column vcc_customer.REG_SOURCE
     *
     * @mbg.generated
     */
    private String regSource;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column vcc_customer.CERT_AUTH
     *
     * @mbg.generated
     */
    private String certAuth;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column vcc_customer.PHONE_AUTH
     *
     * @mbg.generated
     */
    private String phoneAuth;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column vcc_customer.BANKCARD_AUTH
     *
     * @mbg.generated
     */
    private String bankcardAuth;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column vcc_customer.MOBILE_SIGN
     *
     * @mbg.generated
     */
    private String mobileSign;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column vcc_customer.SYN_TIME
     *
     * @mbg.generated
     */
    private Date synTime;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column vcc_customer.CREATE_TIME
     *
     * @mbg.generated
     */
    private Date createTime;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column vcc_customer.UPDATE_TIME
     *
     * @mbg.generated
     */
    private Date updateTime;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column vcc_customer.CUST_ID
     *
     * @return the value of vcc_customer.CUST_ID
     *
     * @mbg.generated
     */
    public Long getCustId() {
        return custId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column vcc_customer.CUST_ID
     *
     * @param custId the value for vcc_customer.CUST_ID
     *
     * @mbg.generated
     */
    public void setCustId(Long custId) {
        this.custId = custId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column vcc_customer.LOGIN_NAME
     *
     * @return the value of vcc_customer.LOGIN_NAME
     *
     * @mbg.generated
     */
    public String getLoginName() {
        return loginName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column vcc_customer.LOGIN_NAME
     *
     * @param loginName the value for vcc_customer.LOGIN_NAME
     *
     * @mbg.generated
     */
    public void setLoginName(String loginName) {
        this.loginName = loginName == null ? null : loginName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column vcc_customer.CUST_NAME
     *
     * @return the value of vcc_customer.CUST_NAME
     *
     * @mbg.generated
     */
    public String getCustName() {
        return custName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column vcc_customer.CUST_NAME
     *
     * @param custName the value for vcc_customer.CUST_NAME
     *
     * @mbg.generated
     */
    public void setCustName(String custName) {
        this.custName = custName == null ? null : custName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column vcc_customer.CERT_NO
     *
     * @return the value of vcc_customer.CERT_NO
     *
     * @mbg.generated
     */
    public String getCertNo() {
        return certNo;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column vcc_customer.CERT_NO
     *
     * @param certNo the value for vcc_customer.CERT_NO
     *
     * @mbg.generated
     */
    public void setCertNo(String certNo) {
        this.certNo = certNo == null ? null : certNo.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column vcc_customer.SEX
     *
     * @return the value of vcc_customer.SEX
     *
     * @mbg.generated
     */
    public String getSex() {
        return sex;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column vcc_customer.SEX
     *
     * @param sex the value for vcc_customer.SEX
     *
     * @mbg.generated
     */
    public void setSex(String sex) {
        this.sex = sex == null ? null : sex.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column vcc_customer.AGE
     *
     * @return the value of vcc_customer.AGE
     *
     * @mbg.generated
     */
    public Short getAge() {
        return age;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column vcc_customer.AGE
     *
     * @param age the value for vcc_customer.AGE
     *
     * @mbg.generated
     */
    public void setAge(Short age) {
        this.age = age;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column vcc_customer.MOBILE
     *
     * @return the value of vcc_customer.MOBILE
     *
     * @mbg.generated
     */
    public String getMobile() {
        return mobile;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column vcc_customer.MOBILE
     *
     * @param mobile the value for vcc_customer.MOBILE
     *
     * @mbg.generated
     */
    public void setMobile(String mobile) {
        this.mobile = mobile == null ? null : mobile.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column vcc_customer.REG_TIME
     *
     * @return the value of vcc_customer.REG_TIME
     *
     * @mbg.generated
     */
    public Date getRegTime() {
        return regTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column vcc_customer.REG_TIME
     *
     * @param regTime the value for vcc_customer.REG_TIME
     *
     * @mbg.generated
     */
    public void setRegTime(Date regTime) {
        this.regTime = regTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column vcc_customer.REG_SOURCE
     *
     * @return the value of vcc_customer.REG_SOURCE
     *
     * @mbg.generated
     */
    public String getRegSource() {
        return regSource;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column vcc_customer.REG_SOURCE
     *
     * @param regSource the value for vcc_customer.REG_SOURCE
     *
     * @mbg.generated
     */
    public void setRegSource(String regSource) {
        this.regSource = regSource == null ? null : regSource.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column vcc_customer.CERT_AUTH
     *
     * @return the value of vcc_customer.CERT_AUTH
     *
     * @mbg.generated
     */
    public String getCertAuth() {
        return certAuth;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column vcc_customer.CERT_AUTH
     *
     * @param certAuth the value for vcc_customer.CERT_AUTH
     *
     * @mbg.generated
     */
    public void setCertAuth(String certAuth) {
        this.certAuth = certAuth == null ? null : certAuth.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column vcc_customer.PHONE_AUTH
     *
     * @return the value of vcc_customer.PHONE_AUTH
     *
     * @mbg.generated
     */
    public String getPhoneAuth() {
        return phoneAuth;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column vcc_customer.PHONE_AUTH
     *
     * @param phoneAuth the value for vcc_customer.PHONE_AUTH
     *
     * @mbg.generated
     */
    public void setPhoneAuth(String phoneAuth) {
        this.phoneAuth = phoneAuth == null ? null : phoneAuth.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column vcc_customer.BANKCARD_AUTH
     *
     * @return the value of vcc_customer.BANKCARD_AUTH
     *
     * @mbg.generated
     */
    public String getBankcardAuth() {
        return bankcardAuth;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column vcc_customer.BANKCARD_AUTH
     *
     * @param bankcardAuth the value for vcc_customer.BANKCARD_AUTH
     *
     * @mbg.generated
     */
    public void setBankcardAuth(String bankcardAuth) {
        this.bankcardAuth = bankcardAuth == null ? null : bankcardAuth.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column vcc_customer.MOBILE_SIGN
     *
     * @return the value of vcc_customer.MOBILE_SIGN
     *
     * @mbg.generated
     */
    public String getMobileSign() {
        return mobileSign;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column vcc_customer.MOBILE_SIGN
     *
     * @param mobileSign the value for vcc_customer.MOBILE_SIGN
     *
     * @mbg.generated
     */
    public void setMobileSign(String mobileSign) {
        this.mobileSign = mobileSign == null ? null : mobileSign.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column vcc_customer.SYN_TIME
     *
     * @return the value of vcc_customer.SYN_TIME
     *
     * @mbg.generated
     */
    public Date getSynTime() {
        return synTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column vcc_customer.SYN_TIME
     *
     * @param synTime the value for vcc_customer.SYN_TIME
     *
     * @mbg.generated
     */
    public void setSynTime(Date synTime) {
        this.synTime = synTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column vcc_customer.CREATE_TIME
     *
     * @return the value of vcc_customer.CREATE_TIME
     *
     * @mbg.generated
     */
    public Date getCreateTime() {
        return createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column vcc_customer.CREATE_TIME
     *
     * @param createTime the value for vcc_customer.CREATE_TIME
     *
     * @mbg.generated
     */
    public void setCreateTime(Date createTime) {
        this.createTime = createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column vcc_customer.UPDATE_TIME
     *
     * @return the value of vcc_customer.UPDATE_TIME
     *
     * @mbg.generated
     */
    public Date getUpdateTime() {
        return updateTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column vcc_customer.UPDATE_TIME
     *
     * @param updateTime the value for vcc_customer.UPDATE_TIME
     *
     * @mbg.generated
     */
    public void setUpdateTime(Date updateTime) {
        this.updateTime = updateTime;
    }
}