package com.fkapi.datebase.domain;

import java.math.BigDecimal;
import java.util.Date;

public class vcc_cust_biz {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column vcc_cust_biz.CUST_ID
     *
     * @mbg.generated
     */
    private Long custId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column vcc_cust_biz.BILL_DATE
     *
     * @mbg.generated
     */
    private Short billDate;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column vcc_cust_biz.REPAY_DATE
     *
     * @mbg.generated
     */
    private Short repayDate;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column vcc_cust_biz.CREDIT_AMT
     *
     * @mbg.generated
     */
    private Long creditAmt;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column vcc_cust_biz.NO_BILL_AMT
     *
     * @mbg.generated
     */
    private BigDecimal noBillAmt;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column vcc_cust_biz.STATUS
     *
     * @mbg.generated
     */
    private String status;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column vcc_cust_biz.CREATE_TIME
     *
     * @mbg.generated
     */
    private Date createTime;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column vcc_cust_biz.UPDATE_TIME
     *
     * @mbg.generated
     */
    private Date updateTime;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column vcc_cust_biz.CUST_ID
     *
     * @return the value of vcc_cust_biz.CUST_ID
     *
     * @mbg.generated
     */
    public Long getCustId() {
        return custId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column vcc_cust_biz.CUST_ID
     *
     * @param custId the value for vcc_cust_biz.CUST_ID
     *
     * @mbg.generated
     */
    public void setCustId(Long custId) {
        this.custId = custId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column vcc_cust_biz.BILL_DATE
     *
     * @return the value of vcc_cust_biz.BILL_DATE
     *
     * @mbg.generated
     */
    public Short getBillDate() {
        return billDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column vcc_cust_biz.BILL_DATE
     *
     * @param billDate the value for vcc_cust_biz.BILL_DATE
     *
     * @mbg.generated
     */
    public void setBillDate(Short billDate) {
        this.billDate = billDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column vcc_cust_biz.REPAY_DATE
     *
     * @return the value of vcc_cust_biz.REPAY_DATE
     *
     * @mbg.generated
     */
    public Short getRepayDate() {
        return repayDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column vcc_cust_biz.REPAY_DATE
     *
     * @param repayDate the value for vcc_cust_biz.REPAY_DATE
     *
     * @mbg.generated
     */
    public void setRepayDate(Short repayDate) {
        this.repayDate = repayDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column vcc_cust_biz.CREDIT_AMT
     *
     * @return the value of vcc_cust_biz.CREDIT_AMT
     *
     * @mbg.generated
     */
    public Long getCreditAmt() {
        return creditAmt;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column vcc_cust_biz.CREDIT_AMT
     *
     * @param creditAmt the value for vcc_cust_biz.CREDIT_AMT
     *
     * @mbg.generated
     */
    public void setCreditAmt(Long creditAmt) {
        this.creditAmt = creditAmt;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column vcc_cust_biz.NO_BILL_AMT
     *
     * @return the value of vcc_cust_biz.NO_BILL_AMT
     *
     * @mbg.generated
     */
    public BigDecimal getNoBillAmt() {
        return noBillAmt;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column vcc_cust_biz.NO_BILL_AMT
     *
     * @param noBillAmt the value for vcc_cust_biz.NO_BILL_AMT
     *
     * @mbg.generated
     */
    public void setNoBillAmt(BigDecimal noBillAmt) {
        this.noBillAmt = noBillAmt;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column vcc_cust_biz.STATUS
     *
     * @return the value of vcc_cust_biz.STATUS
     *
     * @mbg.generated
     */
    public String getStatus() {
        return status;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column vcc_cust_biz.STATUS
     *
     * @param status the value for vcc_cust_biz.STATUS
     *
     * @mbg.generated
     */
    public void setStatus(String status) {
        this.status = status == null ? null : status.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column vcc_cust_biz.CREATE_TIME
     *
     * @return the value of vcc_cust_biz.CREATE_TIME
     *
     * @mbg.generated
     */
    public Date getCreateTime() {
        return createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column vcc_cust_biz.CREATE_TIME
     *
     * @param createTime the value for vcc_cust_biz.CREATE_TIME
     *
     * @mbg.generated
     */
    public void setCreateTime(Date createTime) {
        this.createTime = createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column vcc_cust_biz.UPDATE_TIME
     *
     * @return the value of vcc_cust_biz.UPDATE_TIME
     *
     * @mbg.generated
     */
    public Date getUpdateTime() {
        return updateTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column vcc_cust_biz.UPDATE_TIME
     *
     * @param updateTime the value for vcc_cust_biz.UPDATE_TIME
     *
     * @mbg.generated
     */
    public void setUpdateTime(Date updateTime) {
        this.updateTime = updateTime;
    }
}